#!/bin/bash
source /usr/lib/openfoam/openfoam2112/etc/bashrc

cat $FOAM_RUN
source $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication reconstructPar -time 2
runApplication postProcess -latestTime -func probesTimeFlow10
